# Generated by Django 6.0.3 on 2026-03-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly budget limit for the user', max_digits=12),
        ),
    ]
