# Generated by Django 6.0.3 on 2026-04-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded profile photo'),
        ),
    ]
